name: push servers

on:
    push:
        branches: [ "main" ]

jobs:
    push-servers:
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v3

            # 运行自定义命令(测试)
            - name: run custom command
              run: |
                  pwd
                  ls -al

            # 使用 “>” 和文本内容缩进表示的块, 将块中回车替换为空格，最终连接成一行
            - name: zip
              run: >-
                  zip -r ./memos-web.zip ./*

            - name: upload
              run: >-
                  sshpass -p ${{secrets.SERVER_PASSWORD}}
                  scp -P ${{secrets.SERVER_PORT}}
                  -r -o StrictHostKeyChecking=no
                  ./memos-web.zip
                  ${{secrets.SERVER_USERNAME}}@${{secrets.SERVER_ADDRESS}}:/home/docker/nginx/_project

            - name: del and unzip
              run: >-
                  sshpass -p ${{secrets.SERVER_PASSWORD}}
                  ssh -p ${{secrets.SERVER_PORT}}
                  -o StrictHostKeyChecking=no
                  ${{secrets.SERVER_USERNAME}}@${{secrets.SERVER_ADDRESS}}
                  "cd /home/docker/nginx/_project && rm -rf ./memos-web && unzip ./memos-web.zip -d ./memos-web && rm -rf ./memos-web.zip"

            - name: send notification
              run: curl ${{ secrets.BARK }}/GithubAction/Nginx_memos-web项目已更新
