name: Nginx config push servers

on:
    push:
        branches: [ "main" ]

jobs:
    push-servers:
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v3

            # 运行自定义命令(测试)
            - name: run custom command
              run: |
                  pwd
                  ls -al

            # 使用 “>” 和文本内容缩进表示的块, 将块中回车替换为空格，最终连接成一行
            - name: del server file
              run: >-
                  sshpass -p ${{secrets.CHENCD97_SERVER_PASSWORD}}
                  ssh -p ${{secrets.CHENCD97_SERVER_PORT}}
                  -o StrictHostKeyChecking=no ${{secrets.CHENCD97_SERVER_USERNAME}}@${{secrets.CHENCD97_SERVER_ADDRESS}}
                  "cd /home/docker/nginx && rm -rf ./nginx.conf && rm -rf ./_config/*.conf && rm -rf ./_github-upload.temp"

            - name: upload default config
              run: >-
                  sshpass -p ${{secrets.CHENCD97_SERVER_PASSWORD}}
                  scp -P ${{secrets.CHENCD97_SERVER_PORT}}
                  -r -o StrictHostKeyChecking=no
                  ./nginx-config/nginx.conf ${{secrets.CHENCD97_SERVER_USERNAME}}@${{secrets.CHENCD97_SERVER_ADDRESS}}:/home/docker/nginx

            - name: upload project config
              run: >-
                  sshpass -p ${{secrets.CHENCD97_SERVER_PASSWORD}}
                  scp -P ${{secrets.CHENCD97_SERVER_PORT}}
                  -r -o StrictHostKeyChecking=no
                  ./nginx-config/_config/*.conf ${{secrets.CHENCD97_SERVER_USERNAME}}@${{secrets.CHENCD97_SERVER_ADDRESS}}:/home/docker/nginx/_config

            - name: set server restart
              run: >-
                  sshpass -p ${{secrets.CHENCD97_SERVER_PASSWORD}}
                  ssh -p ${{secrets.CHENCD97_SERVER_PORT}}
                  -o StrictHostKeyChecking=no ${{secrets.CHENCD97_SERVER_USERNAME}}@${{secrets.CHENCD97_SERVER_ADDRESS}}
                  "touch /home/docker/nginx/_github-upload.temp"
